import type { Database } from "@/integrations/supabase/types";

type ProjectRow = Database["public"]["Tables"]["projects"]["Row"];

export type DigitalInvestProject = ProjectRow & {
  portfolio_group: string;
  tags: string[];
  source_url: string;
};

const importedAt = "2026-06-22T00:00:00.000Z";

export const DIGITAL_INVEST_PROJECTS: DigitalInvestProject[] = [
  {
    id: "00000000-0000-4000-8000-000000000001",
    name: "Digital Invest Portfolio",
    slug: "digital-invest-portfolio",
    description:
      "Multi-sector portfolio spanning HealthTech, AgroTech, FoodTech, Robotics, and AI. Shared infrastructure and cross-project synergies create compounding value across 20+ innovative ventures.",
    status: "active",
    priority: "critical",
    color: "#0a2540",
    icon: null,
    category: "FinTech / Multi-Sector Holding",
    start_date: null,
    deadline: null,
    budget: null,
    progress: 82,
    health: "on_track",
    owner_id: null,
    archived_at: null,
    created_by: null,
    created_at: importedAt,
    updated_at: importedAt,
    portfolio_group: "Flagship & Portfolio",
    tags: ["Multi-Sector", "Holding"],
    source_url: "https://www.digitalinvest.com/projects/digital-invest-portfolio",
  },
  {
    id: "00000000-0000-4000-8000-000000000002",
    name: "BioMath Life Platform",
    slug: "biomathlife",
    description:
      "Precision medicine platform with 200+ health services across 20 categories. Integrates genetic analysis, biomathematical modeling, and AI diagnostics for disease prevention and longevity optimization.",
    status: "active",
    priority: "critical",
    color: "#14b8a6",
    icon: null,
    category: "BioTech / Longevity Wellness Platform",
    start_date: null,
    deadline: null,
    budget: null,
    progress: 64,
    health: "on_track",
    owner_id: null,
    archived_at: null,
    created_by: null,
    created_at: importedAt,
    updated_at: importedAt,
    portfolio_group: "BioMath Life Family",
    tags: ["Longevity", "Wellness Platform"],
    source_url: "https://www.digitalinvest.com/projects/biomathlife",
  },
  {
    id: "00000000-0000-4000-8000-000000000003",
    name: "BioMath Core",
    slug: "biomath-core",
    description:
      "Foundational health operating system unifying medical records, genetics, and lifestyle into actionable insights. The data engine powering the BioMath ecosystem for precision clinical decisions.",
    status: "active",
    priority: "critical",
    color: "#ef4444",
    icon: null,
    category: "Digital Health / Foundation Layer",
    start_date: null,
    deadline: null,
    budget: null,
    progress: 52,
    health: "watchlist",
    owner_id: null,
    archived_at: null,
    created_by: null,
    created_at: importedAt,
    updated_at: importedAt,
    portfolio_group: "BioMath Life Family",
    tags: ["AI Health", "Foundation Layer"],
    source_url: "https://www.digitalinvest.com/projects/biomath-core",
  },
  {
    id: "00000000-0000-4000-8000-000000000004",
    name: "SAVEN",
    slug: "saven",
    description:
      "Infrastructure of Continuous Execution bridging digital understanding and physical reality. A 5-step cycle of Context, Action, Verification, Control, and Support helps keep life on track.",
    status: "active",
    priority: "high",
    color: "#3b82f6",
    icon: null,
    category: "Infrastructure / Medical Robotics",
    start_date: null,
    deadline: null,
    budget: null,
    progress: 58,
    health: "on_track",
    owner_id: null,
    archived_at: null,
    created_by: null,
    created_at: importedAt,
    updated_at: importedAt,
    portfolio_group: "BioMath Life Family",
    tags: ["Robotics", "Medical Infrastructure"],
    source_url: "https://www.digitalinvest.com/projects/saven",
  },
  {
    id: "00000000-0000-4000-8000-000000000005",
    name: "Stress",
    slug: "stresscore",
    description:
      "Psychological state intelligence tracking stress, mood, and energy with AI micro-insights. Identifies triggers, predicts low-energy windows, and delivers timely interventions for emotional resilience.",
    status: "planning",
    priority: "high",
    color: "#8b5cf6",
    icon: null,
    category: "Mental Health / HRV Stress",
    start_date: null,
    deadline: null,
    budget: null,
    progress: 24,
    health: "watchlist",
    owner_id: null,
    archived_at: null,
    created_by: null,
    created_at: importedAt,
    updated_at: importedAt,
    portfolio_group: "BioMath Life Family",
    tags: ["Mental Health", "HRV"],
    source_url: "https://www.digitalinvest.com/projects/stresscore",
  },
  {
    id: "00000000-0000-4000-8000-000000000006",
    name: "Vital",
    slug: "vitalcore",
    description:
      "Unified vital signs dashboard combining HR, HRV, sleep, stress, and activity patterns. Detects anomalies before emergencies and provides actionable alerts for proactive health management.",
    status: "planning",
    priority: "high",
    color: "#06b6d4",
    icon: null,
    category: "Vitals / Wearables",
    start_date: null,
    deadline: null,
    budget: null,
    progress: 28,
    health: "watchlist",
    owner_id: null,
    archived_at: null,
    created_by: null,
    created_at: importedAt,
    updated_at: importedAt,
    portfolio_group: "BioMath Life Family",
    tags: ["Vitals", "Wearables"],
    source_url: "https://www.digitalinvest.com/projects/vitalcore",
  },
  {
    id: "00000000-0000-4000-8000-000000000007",
    name: "BioAge",
    slug: "bioagecore",
    description:
      "AI-powered biological age analysis comparing chronological age to real body condition. Continuous optimization tracking and personalized interventions help users control their aging trajectory.",
    status: "planning",
    priority: "medium",
    color: "#22c55e",
    icon: null,
    category: "Longevity / Biological Age",
    start_date: null,
    deadline: null,
    budget: null,
    progress: 22,
    health: "on_track",
    owner_id: null,
    archived_at: null,
    created_by: null,
    created_at: importedAt,
    updated_at: importedAt,
    portfolio_group: "BioMath Life Family",
    tags: ["Biological Age", "Longevity"],
    source_url: "https://www.digitalinvest.com/projects/bioagecore",
  },
  {
    id: "00000000-0000-4000-8000-000000000008",
    name: "Senior",
    slug: "seniorcore",
    description:
      "Support system for seniors and caregivers monitoring wellness patterns, medication adherence, and activity levels. Real-time health insights support safety, independence, and family peace of mind.",
    status: "planning",
    priority: "medium",
    color: "#f97316",
    icon: null,
    category: "Senior Care / Caregivers",
    start_date: null,
    deadline: null,
    budget: null,
    progress: 20,
    health: "on_track",
    owner_id: null,
    archived_at: null,
    created_by: null,
    created_at: importedAt,
    updated_at: importedAt,
    portfolio_group: "BioMath Life Family",
    tags: ["Senior Care", "Caregivers"],
    source_url: "https://www.digitalinvest.com/projects/seniorcore",
  },
  {
    id: "00000000-0000-4000-8000-000000000009",
    name: "Skin",
    slug: "skincore",
    description:
      "Camera-based AI skin analysis tracking texture, tone, and condition changes over time. Ingredient-level feedback and visual trend tracking help users understand what truly works for their skin.",
    status: "planning",
    priority: "medium",
    color: "#ec4899",
    icon: null,
    category: "Beauty / Skin Analysis",
    start_date: null,
    deadline: null,
    budget: null,
    progress: 18,
    health: "on_track",
    owner_id: null,
    archived_at: null,
    created_by: null,
    created_at: importedAt,
    updated_at: importedAt,
    portfolio_group: "BioMath Life Family",
    tags: ["Beauty", "Skin Analysis"],
    source_url: "https://www.digitalinvest.com/projects/skincore",
  },
  {
    id: "00000000-0000-4000-8000-000000000010",
    name: "Luna Balance",
    slug: "luna-balance",
    description:
      "Mindfulness platform helping women understand themselves through Silence Technology and Relationship Mode. Acceptance over pressure, translating internal sensations into human language.",
    status: "planning",
    priority: "medium",
    color: "#a855f7",
    icon: null,
    category: "Women's Health / Hormonal Cycle",
    start_date: null,
    deadline: null,
    budget: null,
    progress: 18,
    health: "on_track",
    owner_id: null,
    archived_at: null,
    created_by: null,
    created_at: importedAt,
    updated_at: importedAt,
    portfolio_group: "BioMath Life Family",
    tags: ["Women's Health", "Hormonal Cycle"],
    source_url: "https://www.digitalinvest.com/projects/luna-balance",
  },
  {
    id: "00000000-0000-4000-8000-000000000011",
    name: "T1/2D",
    slug: "t1d",
    description:
      "A practical system that helps people with Type 1 and Type 2 diabetes understand what is happening, respond in time, and manage daily life with less stress.",
    status: "idea",
    priority: "high",
    color: "#0ea5e9",
    icon: null,
    category: "Diabetes Care / Daily Life",
    start_date: null,
    deadline: null,
    budget: null,
    progress: 14,
    health: "watchlist",
    owner_id: null,
    archived_at: null,
    created_by: null,
    created_at: importedAt,
    updated_at: importedAt,
    portfolio_group: "BioMath Life Family",
    tags: ["Diabetes", "Daily Life"],
    source_url: "https://www.digitalinvest.com/projects/t1d",
  },
  {
    id: "00000000-0000-4000-8000-000000000012",
    name: "MRX.Health",
    slug: "mrx-health",
    description:
      "Medication Reactions Explorer tracking prescriptions and monitoring body effects in real time. Interactive bio-scan analysis helps identify adverse interactions early.",
    status: "planning",
    priority: "high",
    color: "#10b981",
    icon: null,
    category: "MedTech / Clinical Telehealth",
    start_date: null,
    deadline: null,
    budget: null,
    progress: 24,
    health: "watchlist",
    owner_id: null,
    archived_at: null,
    created_by: null,
    created_at: importedAt,
    updated_at: importedAt,
    portfolio_group: "BioMath Life Family",
    tags: ["Clinical", "Telehealth"],
    source_url: "https://www.digitalinvest.com/projects/mrx-health",
  },
  {
    id: "00000000-0000-4000-8000-000000000013",
    name: "BaseLine",
    slug: "baseline",
    description:
      "Professional health logic made simple. A 4-step clinical launch translating clinical noise into clarity: Biological Handshake, Baseline Ingestion, Marker Synthesis, and Prognostic Launch.",
    status: "planning",
    priority: "medium",
    color: "#64748b",
    icon: null,
    category: "HealthTech / Continuous Monitoring",
    start_date: null,
    deadline: null,
    budget: null,
    progress: 20,
    health: "on_track",
    owner_id: null,
    archived_at: null,
    created_by: null,
    created_at: importedAt,
    updated_at: importedAt,
    portfolio_group: "BioMath Life Family",
    tags: ["Diagnostics", "Monitoring"],
    source_url: "https://www.digitalinvest.com/projects/baseline",
  },
  {
    id: "00000000-0000-4000-8000-000000000014",
    name: "AGRON - Aerial-Ground Robotics Operations Network",
    slug: "agron",
    description:
      "National infrastructure for autonomous aerial and ground robotics: training, certification, fleet operations, and standards. The operational backbone of the U.S. robotics economy.",
    status: "active",
    priority: "critical",
    color: "#22c55e",
    icon: null,
    category: "Robotics / Field Operations",
    start_date: null,
    deadline: null,
    budget: null,
    progress: 48,
    health: "watchlist",
    owner_id: null,
    archived_at: null,
    created_by: null,
    created_at: importedAt,
    updated_at: importedAt,
    portfolio_group: "AGRON Family",
    tags: ["Autonomous Robots", "Field Operations"],
    source_url: "https://www.digitalinvest.com/projects/agron",
  },
  {
    id: "00000000-0000-4000-8000-000000000015",
    name: "AGRON Work",
    slug: "agron-work",
    description:
      "Talent platform connecting employers with verified professionals in drones, robotics, AI, and automation. Direct hiring, skill certification, and workforce intelligence for the autonomy era.",
    status: "planning",
    priority: "high",
    color: "#84cc16",
    icon: null,
    category: "Workforce / Operations",
    start_date: null,
    deadline: null,
    budget: null,
    progress: 26,
    health: "on_track",
    owner_id: null,
    archived_at: null,
    created_by: null,
    created_at: importedAt,
    updated_at: importedAt,
    portfolio_group: "AGRON Family",
    tags: ["Workforce", "Operations"],
    source_url: "https://www.digitalinvest.com/projects/agron-work",
  },
  {
    id: "00000000-0000-4000-8000-000000000016",
    name: "TerraAero",
    slug: "terraaero",
    description:
      "Drone agricultural services across the Southern U.S. for precision monitoring, crop analytics, and resource optimization. Building U.S. drone manufacturing with a 23-state expansion roadmap.",
    status: "active",
    priority: "high",
    color: "#0ea5e9",
    icon: null,
    category: "AgriTech / Precision Agriculture",
    start_date: null,
    deadline: null,
    budget: null,
    progress: 42,
    health: "on_track",
    owner_id: null,
    archived_at: null,
    created_by: null,
    created_at: importedAt,
    updated_at: importedAt,
    portfolio_group: "TerraAero",
    tags: ["Drones", "Precision Agriculture"],
    source_url: "https://www.digitalinvest.com/projects/terraaero",
  },
  {
    id: "00000000-0000-4000-8000-000000000017",
    name: "MyDay",
    slug: "myday",
    description:
      "AI-powered daily planning SaaS transforming routines into measurable behavioral patterns. Structured nutrition tracking, energy management, and micro-goal architecture backed by analytics.",
    status: "active",
    priority: "medium",
    color: "#06b6d4",
    icon: null,
    category: "Lifestyle / AI Planning",
    start_date: null,
    deadline: null,
    budget: null,
    progress: 50,
    health: "on_track",
    owner_id: null,
    archived_at: null,
    created_by: null,
    created_at: importedAt,
    updated_at: importedAt,
    portfolio_group: "Lifestyle & Other",
    tags: ["AI Planning", "Habits"],
    source_url: "https://www.digitalinvest.com/projects/myday",
  },
  {
    id: "00000000-0000-4000-8000-000000000018",
    name: "It's Good Today",
    slug: "itsgoodtoday",
    description:
      "Wellness companion built on simplicity: small daily actions in food, movement, mood, and lifestyle. No complexity, no pressure. Today is good; tomorrow can be a little better.",
    status: "planning",
    priority: "medium",
    color: "#f59e0b",
    icon: null,
    category: "Wellness / Daily Practice",
    start_date: null,
    deadline: null,
    budget: null,
    progress: 24,
    health: "on_track",
    owner_id: null,
    archived_at: null,
    created_by: null,
    created_at: importedAt,
    updated_at: importedAt,
    portfolio_group: "Lifestyle & Other",
    tags: ["Wellness", "Daily Practice"],
    source_url: "https://www.digitalinvest.com/projects/itsgoodtoday",
  },
  {
    id: "00000000-0000-4000-8000-000000000019",
    name: "TableServed",
    slug: "table-served",
    description:
      "Deterministic family nutrition with scheduled meals from certified U.S. hubs every Sunday. Weekly stability boxes use a Friday Lock and Sunday Pulse production cycle with diverse local cuisines.",
    status: "planning",
    priority: "medium",
    color: "#fb923c",
    icon: null,
    category: "FoodTech / Hospitality",
    start_date: null,
    deadline: null,
    budget: null,
    progress: 34,
    health: "on_track",
    owner_id: null,
    archived_at: null,
    created_by: null,
    created_at: importedAt,
    updated_at: importedAt,
    portfolio_group: "Lifestyle & Other",
    tags: ["Restaurants", "Hospitality"],
    source_url: "https://www.digitalinvest.com/projects/table-served",
  },
  {
    id: "00000000-0000-4000-8000-000000000020",
    name: "1inow",
    slug: "1inow",
    description:
      "Personal and business intelligence environment connecting tasks, notes, projects, files, meetings, and messages into a single living context so people remember less and understand more.",
    status: "active",
    priority: "critical",
    color: "#111827",
    icon: null,
    category: "Productivity / Intelligence Environment",
    start_date: null,
    deadline: null,
    budget: null,
    progress: 66,
    health: "on_track",
    owner_id: null,
    archived_at: null,
    created_by: null,
    created_at: importedAt,
    updated_at: importedAt,
    portfolio_group: "Lifestyle & Other",
    tags: ["AI Planning", "Intelligence Environment"],
    source_url: "https://www.digitalinvest.com/projects/1inow",
  },
];

const catalogBySlug = new Map(DIGITAL_INVEST_PROJECTS.map((project) => [project.slug, project]));

export function mergeDigitalInvestProjects(
  projects: ProjectRow[] | null | undefined,
): DigitalInvestProject[] {
  const merged = new Map<string, DigitalInvestProject>();

  for (const project of DIGITAL_INVEST_PROJECTS) {
    merged.set(project.slug, project);
  }

  for (const project of projects ?? []) {
    const catalog = catalogBySlug.get(project.slug);
    merged.set(project.slug, {
      ...(catalog ?? {
        portfolio_group: project.category ?? "Workspace",
        tags: project.category ? [project.category] : [],
        source_url: "",
      }),
      ...project,
      description: catalog?.description ?? project.description,
      category: catalog?.category ?? project.category,
      color: project.color ?? catalog?.color ?? "#06b6d4",
      progress: project.progress ?? catalog?.progress ?? 0,
      health: project.health ?? catalog?.health ?? "on_track",
      portfolio_group: catalog?.portfolio_group ?? project.category ?? "Workspace",
      tags: catalog?.tags ?? (project.category ? [project.category] : []),
      source_url: catalog?.source_url ?? "",
    });
  }

  return [...merged.values()].sort((a, b) => {
    const left = DIGITAL_INVEST_PROJECTS.findIndex((project) => project.slug === a.slug);
    const right = DIGITAL_INVEST_PROJECTS.findIndex((project) => project.slug === b.slug);
    if (left !== -1 || right !== -1)
      return (left === -1 ? 999 : left) - (right === -1 ? 999 : right);
    return new Date(b.created_at).getTime() - new Date(a.created_at).getTime();
  });
}

export function getDigitalInvestProjectBySlug(slug: string): DigitalInvestProject | null {
  return catalogBySlug.get(slug) ?? null;
}
